"""All user-facing Telegram strings; no messages embedded in handlers/use cases."""
from backend.apps.cinema.enums.bot_enums import Language

MESSAGES = {
    Language.FA: {
        "welcome": "🎬 فیلم موردنظر را انتخاب کنید:",
        "publish_announcement": "🎬 {film}\n\n📺 کانال فیلم: {channel}\n🔗 دریافت: {link}",
        "publish_button": "🎬 دریافت فیلم",
        "missing": "این فیلم موجود نیست یا غیرفعال شده است.",
        "join_channels": "⚠️ هنوز عضو همه کانال‌ها نشده‌اید.",
        "join_and_follow": "⚠️ کانال‌های باقی‌مانده را عضو شوید و صفحه‌های زیر را باز کنید.",
        "follow_pages": "📷 روی دکمه فالو کردن صفحه‌های باقی‌مانده بزنید.",
        "setup_unavailable": "⚙️ تنظیمات کانال‌های این فیلم کامل نیست. به مدیر اطلاع دهید.",
        "membership_check_unavailable": "⚠️ بررسی عضویت ممکن نشد. لطفاً دوباره تلاش کنید؛ اگر ادامه داشت، ادمین بودن ربات و شناسه کانال را به مدیر اطلاع دهید.",
        "channel": "📣 عضویت در {name}",
        "instagram": "📷 فالو کردن {name}",
        "check": "✅ بررسی و دریافت",
        "watch": "🎬 دریافت فیلم",
        "menu": "🏠 منوی فیلم‌ها",
        "language": "🌐 زبان / Language",
        "lang_saved": "زبان به فارسی تغییر کرد.",
        "ready": "✅ شرایط دریافت فیلم تکمیل شد.",
        "sending": "🎞 در حال ارسال فیلم… پیام‌ها پس از حدود {seconds} ثانیه حذف می‌شوند.",
        "sent": "✅ فایل‌ها ارسال شدند و پس از حدود {seconds} ثانیه حذف می‌شوند.",
        "delivery_failed": "ارسال فایل ممکن نشد. لطفاً دوباره تلاش کنید.",
        "no_media": "هنوز فایلی برای این فیلم ثبت نشده است.",
        "too_many": "لطفاً کمی بعد دوباره امتحان کنید.",
        "error": "در انجام درخواست خطایی رخ داد. دوباره تلاش کنید.",
        "admin_only": "این دستور مخصوص مدیر ربات است.",
        "source_saved": "رسانه ثبت شد: چت {chat_id}، پیام {message_id}؛ آن را به فیلم وصل کنید.",
        "film_channel_unavailable": "کانال اختصاصی فیلم تنظیم نشده است.",
        "central_channel_unavailable": "کانال مرکزی تنظیم نشده است.",
        "membership_unavailable": "بررسی عضویت در {name} ممکن نشد.",
        "unsupported": "از /start استفاده کنید.",
        "visit_expired": "لینک فالو کردن نامعتبر یا منقضی شده است؛ از ربات لینک تازه بگیرید.",
        "films_empty": "فعلاً فیلم فعالی در فهرست نیست.",
        "next_page": "بعدی ◀️", "prev_page": "▶️ قبلی",
    },
    Language.EN: {
        "welcome": "🎬 Choose a film:",
        "publish_announcement": "🎬 {film}\n\nFilm channel: {channel}\nGet the film: {link}",
        "publish_button": "🎬 Get film",
        "missing": "This film is unavailable.",
        "join_channels": "⚠️ You have not joined all the required channels yet.",
        "join_and_follow": "⚠️ Join the remaining channels and open the pages below.",
        "follow_pages": "📷 Tap Follow for the remaining Instagram pages.",
        "setup_unavailable": "⚙️ This film's channels are not fully configured. Contact the administrator.",
        "membership_check_unavailable": "⚠️ Could not verify channel membership. Try again; if this continues, ask the administrator to check bot admin access and channel IDs.",
        "channel": "📣 Join {name}",
        "instagram": "📷 Follow {name}",
        "check": "✅ Check & receive",
        "watch": "🎬 Receive film",
        "menu": "🏠 Film menu",
        "language": "🌐 Language / زبان",
        "lang_saved": "Language switched to English.",
        "ready": "✅ Requirements complete.",
        "sending": "🎞 Sending film… Messages will be deleted in about {seconds} seconds.",
        "sent": "✅ Files sent; they will be deleted in about {seconds} seconds.",
        "delivery_failed": "The file could not be sent. Please try again.",
        "no_media": "No files are assigned to this film yet.",
        "too_many": "Please wait a little before trying again.",
        "error": "Something went wrong. Try again.",
        "admin_only": "This command is available only to administrators.",
        "source_saved": "Media recorded: chat {chat_id}, message {message_id}; assign it to a film.",
        "film_channel_unavailable": "The film channel has not been configured.",
        "central_channel_unavailable": "The central channel has not been configured.",
        "membership_unavailable": "Could not check membership of {name}.",
        "unsupported": "Use /start.",
        "visit_expired": "This follow link is invalid or expired; request a new one from the bot.",
        "films_empty": "No active films are listed yet.",
        "next_page": "Next ▶️", "prev_page": "◀️ Previous",
    },
}


def t(language: str, key: str, **kwargs) -> str:
    return MESSAGES.get(language, MESSAGES[Language.FA])[key].format(**kwargs)
